### ISSUE TITLE
This Plugin Breaks the Neovim Start Screen

### ISSUE THREAD

**Issue by amarakon** [folke/todo-comments.nvim#133]
When opening Neovim without arguments and without this plugin, I can see the start screen. With this plugin, I see it only for a millisecond and then it disappears. I can conclude that this plugin is causing the Neovim start screen to not show. I do not know why though.

**Comment by sadtab** [comment]
Same here

**Comment by folke** [comment]
Feel free to submit a PR. I don't use the Neovim start screen, so won't spend the time to look into this. Todo-comments doesn't do anything weird, no idea what's causing this

**Comment by MPWrobel** [comment]
I looked into this and concluded that it's caused by `config.colors()` function being called from a deferred function (`setup()`), more precisely these 3 lines:
```
vim.cmd("hi def TodoBg" .. kw .. " guibg=" .. hex .. " guifg=" .. fg .. " gui=" .. bg_gui)
vim.cmd("hi def TodoFg" .. kw .. " guibg=NONE guifg=" .. hex .. " gui=" .. fg_gui)
vim.cmd("hi def TodoSign" .. kw .. " guibg=" .. sign_bg .. " guifg=" .. hex .. " gui=NONE")
```
`:highlight` command triggers redrawing, which causes the start screen to disappear. I managed to fix this behaviour by adding `event='VimEnter'` to my packer setup. It looks like this:
```
use {
	'folke/todo-comments.nvim',
	requires = 'nvim-lua/plenary.nvim',
	event = 'VimEnter',
	config = function()
		require('todo-comments').setup()
	end
}
```
Remember to run `:PackerCompile` if you change your configuration.

**Comment by Tony-Sol** [comment]
@MPWrobel's solution works for me
