### ISSUE TITLE
Add option for :TodoTelescope to ignore dirs

### ISSUE THREAD

**Issue by Grazfather** [folke/todo-comments.nvim#222]
### Did you check the docs?

- [X] I have read all the todo-comments.nvim docs

### Is your feature request related to a problem? Please describe.

TodoTelescope is useless in any Go project that vendors its deps because it shows the TODOs of all its deps

### Describe the solution you'd like

Allow some ignore regex filepath, maybe. I could say I don't want it to search anything in vendor/

### Describe alternatives you've considered

x

**Comment by Benjman** [comment]
This can usually be achieved through the command you're using to search for TODO comments. By default todo-comments uses ripgrep, so you can ignore directories with the `--glob` flag. In my case, I'm ignoring files in the `lib/` directory:

```lua
{
  search = {
    command = "rg",
    args = {
      "--glob=!lib/",
    },
  },
}
```

Unfortunately, I've found I needed to include the [default flags](https://github.com/folke/todo-comments.nvim/blob/3bddf1dc406b9212c881882c8cfc4798ee271762/lua/todo-comments/config.lua#L69) as well, otherwise the output wouldn't be formatted in the way todo-comments expects:

```lua
{
  search = {
    command = "rg",
    args = {
      "--glob=!lib/",
      "--color=never",
      "--no-heading",
      "--with-filename",
      "--line-number",
      "--column",
    },
  },
}
```

**Comment by bigFin** [comment]
or use .gitignore

**Comment by kumar-shivang** [comment]
> This can usually be achieved through the command you're using to search for TODO comments. By default todo-comments uses ripgrep, so you can ignore directories with the `--glob` flag. In my case, I'm ignoring files in the `lib/` directory:
> 
> ```lua
> {
>   search = {
>     command = "rg",
>     args = {
>       "--glob=!lib/",
>     },
>   },
> }
> ```
> 
> Unfortunately, I've found I needed to include the [default flags](https://github.com/folke/todo-comments.nvim/blob/3bddf1dc406b9212c881882c8cfc4798ee271762/lua/todo-comments/config.lua#L69) as well, otherwise the output wouldn't be formatted in the way todo-comments expects:
> 
> ```lua
> {
>   search = {
>     command = "rg",
>     args = {
>       "--glob=!lib/",
>       "--color=never",
>       "--no-heading",
>       "--with-filename",
>       "--line-number",
>       "--column",
>     },
>   },
> }
> ```

This solution is not working for me, I tried everything.
