### ISSUE TITLE
Add support for highlighting to keywords

### ISSUE THREAD

**Issue by taraslis453** [folke/todo-comments.nvim#54]
Add support for highlighting to keywords without : after them. 
For example 
// TODO some todo
should hightlights even if no : after TODO

**Comment by folke** [comment]
You can already do this, just remove the `:` from the highlight and search pattern as explained in the [config section of the readme](https://github.com/folke/todo-comments.nvim#%EF%B8%8F-configuration)

**Comment by niekvandepas** [comment]
Is there a reason this isn't the default? I spent a good 10 minutes thinking the plugin was broken because my TODO comments don't include a ':' (and [a quick Github Code search shows I'm not alone in that](https://github.com/search?type=code&q=TODO)). What is the downside to making `[[.*<(KEYWORDS)\s*]]` the default pattern?
