### ISSUE TITLE
Idea: conceal comment marker for matched lines

### ISSUE THREAD

**Issue by gegoune** [folke/todo-comments.nvim#6]
I think this could be quite cool actually. Given nature of what this plugin does there is no need to see comment strings on lines that were highlighted by todo. What do you think?

**Comment by folke** [comment]
Good point! I'll see to add this :)

**Comment by folke** [comment]
It's actually not that easy to implement this in a clean way.

By default, treesitter disabled `syntax`, so any syn rules with conceal would not run.

You can enable the hidden treesitter option `additional_vim_regex_highlighting = true`, to have it also run any syntax rules, but that might of course have a lot of side effects.

I'd rather wait until Neovim adds proper `conceal` support to the decorator api.

**Comment by cloggier** [comment]
Ah,I see, didn't realise that. Thanks for detailed explanation. Personally I don't want to enable that setting in treesitter.

I still think it would be nice if that could be implemented but not at cost of hacks or some ugly code. If you are keen on this feature please keep that issue open. Close it otherwise. Once again, big thanks!
