### ISSUE TITLE
Exclude folder in Project

### ISSUE THREAD

**Issue by zettlrobert** [folke/todo-comments.nvim#71]
Is there a way to exclude a complete folder for example node_modules?
Excluding filetype does not work also adding 'node_moduls/' does not work.

If not is there  a way to contribute or to get that functionality into the project?

**Comment by nagy135** [comment]
Hi, I wanted this (because telescope search gave me tons of TODOs that were not mine).

There is option in setup function that handles how TODOs are searched (taken from example when I started using this) ... it has key `search`:
```
    search = {
        command = "rg",
        args = {
            "--color=never",
            "--no-heading",
            "--with-filename",
            "--line-number",
            "--column",
            "--glob=!public"
        },
        -- regex that will be used to match keywords.
        -- don't replace the (KEYWORDS) placeholder
        pattern = [[\b(KEYWORDS):]], -- ripgrep regex
        -- pattern = [[\b(KEYWORDS)\b]], -- match without the extra colon. You'll likely get false positives
    },
```

You could provide any other searching tool I guess, but default has rg (ripgrep) so if you dont want it to match some folders, ripgrep cli options should be used.
As you can see mine has `--glob=!folder_i_dont_want` and you could have any number of those.

I d say this is possible and should be closed.

**Comment by zettlrobert** [comment]
@nagy135 thanks, will try and will close the issue.

**Comment by diego-rapoport** [comment]
> -- regex that will be used to match keywords.
>         -- don't replace the (KEYWORDS) placeholder
>         pattern = [[\b(KEYWORDS):]], -- ripgrep regex
>         -- pattern = [[\b(KEYWORDS)\b]], -- match without the extra colon. You'll likely get false positives

Hi!! I recently tried your solution but I couldn't get it right. Can you help me somehow?

**Comment by diego-rapoport** [comment]
Sorry, I didn't pay attention to the `--glob` args and got stucked till @boring10 helped me.
