### ISSUE TITLE
How do I change the grey colour behide the icon?

### ISSUE THREAD

**Issue by hsheikhali1** [folke/todo-comments.nvim#74]
So I've noticed that there is a persistent grey bg behind the icons and I am not sure how to remove this. Any ideas?

Here is a screenshot of what I mean
![Screen Shot 2021-10-29 at 11 01 36 AM](https://user-images.githubusercontent.com/14851850/139457906-5d109a2f-28cd-4258-ae19-20a0097bece4.png)

**Comment by typkrft** [comment]
When I install this it works initially, but upon restart I get a grey background as well. I am using NVChad and suspect that something is getting loaded out of order or something is overriding the color.

**Comment by hezirel** [comment]
I add some trouble with this for certains themes, the default one mostly.

On macos i found that moving the default themes from brew install dir (/usr/share/vim/vim82/colors) to my XDG_DATA_HOME ('~/.config/vim/.vim/colors') fixed the problem for most of them. Instead of a grey color they adapted to the current theme

I think it has to do with write permissions on highlight groups

Hope it helps
