### ISSUE TITLE
Slow on large files

### ISSUE THREAD

**Issue by romgrk-comparative** [folke/todo-comments.nvim#94]
The plugin seems to be slow on large files. It might be nice to disable it on files exceeding a certain size, or to make in run asynchronously.

cc @romgrk

**Comment by pkazmier** [comment]
When you say slow, can you clarify? Is it only as you are typing your todo? The reason I ask is that I've noticed lag while typing the content of my todo in insert mode (even on small files). While playing around with new notification plug-ins, I believe I know why this is happening. On each character I type, I see a notification for the LSP diagnosing the file.  I was going to open a new bug report, but then saw your issue. However, you did not expound upon what you meant by "slow", so I cannot tell if this might be the root cause for your issue as well.

**Comment by folke** [comment]
I would be very surprised that this plugin slows down in large files.

We only process what's visible on the screen, regardless of file size
